# Generated by Django 6.0 on 2025-12-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_solarsystem_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarsystem',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='longitude',
        ),
    ]
