# Generated by Django 6.0 on 2025-12-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0004_remove_solarsystem_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsystem',
            name='latitude',
            field=models.FloatField(default=23.0225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='longitude',
            field=models.FloatField(default=72.5714),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='location_name',
            field=models.CharField(max_length=255),
        ),
    ]
