# Generated by Django 6.0 on 2026-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0007_rename_timestamp_prediction_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='solarsystem',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_system_name_per_user'),
        ),
    ]
